ALTER TABLE t_city DROP CONSTRAINT FK_t_city_ID
ALTER TABLE t_country DROP CONSTRAINT FK_t_country_ID
DROP TABLE BOOK
DROP TABLE NEWS
DROP TABLE t_address
DROP TABLE t_city
DROP TABLE t_country
DROP TABLE CD
DELETE FROM SEQUENCE WHERE SEQ_NAME = 'SEQ_GEN'
