CREATE TABLE BOOK
(
  ID            BIGINT      NOT NULL,
  DESCRIPTION   VARCHAR(2000),
  ILLUSTRATIONS BOOLEAN,
  ISBN          VARCHAR,
  NBOFPAGES     INTEGER,
  PRICE         DOUBLE,
  PUBLISHER     VARCHAR,
  TITLE         VARCHAR(50) NOT NULL,
  PRIMARY KEY (ID)
)
