CREATE TABLE PERSON (ID BIGINT NOT NULL, DTYPE VARCHAR(31), FIRSTNAME VARCHAR, LASTNAME VARCHAR, EMAIL VARCHAR, PHONENUMBER VARCHAR, PRIMARY KEY (ID))
CREATE TABLE SEQUENCE (SEQ_NAME VARCHAR(50) NOT NULL, SEQ_COUNT NUMERIC(38), PRIMARY KEY (SEQ_NAME))
INSERT INTO SEQUENCE(SEQ_NAME, SEQ_COUNT) values ('SEQ_GEN', 0)
