CREATE TABLE BOOK
(
  ID          BIGINT       NOT NULL,
  DESCRIPTION VARCHAR(2000),
  ISBN        VARCHAR(13),
  NBOFPAGES   INTEGER,
  PRICE       FLOAT,
  TITLE       VARCHAR(255) NOT NULL,
  PRIMARY KEY (ID)
)
