CREATE TABLE book_xml_mapping (ID BIGINT NOT NULL, DESCRIPTION VARCHAR(2000), ILLUSTRATIONS BOOLEAN, ISBN VARCHAR, nb_of_pages INTEGER NOT NULL, PRICE DOUBLE, book_title VARCHAR NOT NULL, PRIMARY KEY (ID))
CREATE TABLE SEQUENCE (SEQ_NAME VARCHAR(50) NOT NULL, SEQ_COUNT NUMERIC(38), PRIMARY KEY (SEQ_NAME))
INSERT INTO SEQUENCE(SEQ_NAME, SEQ_COUNT) values ('SEQ_GEN', 0)
