CREATE TABLE BOOK
(
  ID            BIGINT  NOT NULL,
  DESCRIPTION   VARCHAR(2000),
  ILLUSTRATIONS BOOLEAN,
  ISBN          VARCHAR,
  nb_of_pages   INTEGER NOT NULL,
  PRICE         DOUBLE,
  book_title    VARCHAR NOT NULL,
  PRIMARY KEY (ID)
)
