ALTER TABLE Tag DROP CONSTRAINT FK_Tag_Book_ID
ALTER TABLE track DROP CONSTRAINT FK_track_CD_ID
DROP TABLE BOOK
DROP TABLE CD
DROP TABLE Tag
DROP TABLE track
DELETE FROM SEQUENCE WHERE SEQ_NAME = 'SEQ_GEN'
