CREATE TABLE ARTIST
(
  ID          BIGINT  NOT NULL,
  BIO         VARCHAR(2000),
  DATEOFBIRTH DATE,
  EMAIL       VARCHAR,
  FIRSTNAME   VARCHAR NOT NULL,
  LASTNAME    VARCHAR NOT NULL,
  PRIMARY KEY (ID)
)
