CREATE TABLE COMMENT
(
  ID                BIGINT NOT NULL,
  CONTENT           VARCHAR,
  NICKNAME          VARCHAR,
  NOTE              INTEGER,
  COMMENTS_ID       BIGINT,
  PUBLICATION_INDEX INTEGER,
  PRIMARY KEY (ID)
)
