CREATE TABLE BOOK_XML_MAPPING
(
  ID            BIGINT       NOT NULL,
  BOOK_TITLE    VARCHAR(255) NOT NULL,
  PRICE         FLOAT,
  DESCRIPTION   VARCHAR(2000),
  ISBN          VARCHAR(255),
  NB_OF_PAGES   INTEGER      NOT NULL,
  ILLUSTRATIONS BOOLEAN,
  PRIMARY KEY (ID)
)
