CREATE TABLE CUSTOMER (ID BIGINT NOT NULL, EMAIL VARCHAR, first_name VARCHAR(50) NOT NULL, last_name VARCHAR(50) NOT NULL, phone_number VARCHAR(15), CITY VARCHAR(50) NOT NULL, COUNTRY VARCHAR, STATE VARCHAR(3), STREET1 VARCHAR NOT NULL, STREET2 VARCHAR, zip_code VARCHAR(10), PRIMARY KEY (ID))
CREATE TABLE SEQUENCE (SEQ_NAME VARCHAR(50) NOT NULL, SEQ_COUNT NUMERIC(38), PRIMARY KEY (SEQ_NAME))
INSERT INTO SEQUENCE(SEQ_NAME, SEQ_COUNT) values ('SEQ_GEN', 0)
