ALTER TABLE CUSTOMER DROP CONSTRAINT FK_CUSTOMER_ADDRESS_ID
ALTER TABLE ADDRESS DROP CONSTRAINT FK_ADDRESS_COUNTRY_ID
DROP TABLE CUSTOMER
DROP TABLE ADDRESS
DROP TABLE COUNTRY
DROP TABLE BOOK
DELETE FROM SEQUENCE WHERE SEQ_NAME = 'SEQ_GEN'
