CREATE TABLE BOOK (ID BIGINT NOT NULL, DESCRIPTION VARCHAR, ISBN VARCHAR, PRICE DOUBLE, TITLE VARCHAR, VERSION INTEGER, PRIMARY KEY (ID))
CREATE TABLE SEQUENCE (SEQ_NAME VARCHAR(50) NOT NULL, SEQ_COUNT NUMERIC(38), PRIMARY KEY (SEQ_NAME))
INSERT INTO SEQUENCE(SEQ_NAME, SEQ_COUNT) values ('SEQ_GEN', 0)
