CREATE TABLE CUSTOMER
(
  ID          BIGINT NOT NULL,
  EMAIL       VARCHAR,
  FIRSTNAME   VARCHAR,
  LASTNAME    VARCHAR,
  PHONENUMBER VARCHAR,
  CITY        VARCHAR,
  COUNTRY     VARCHAR,
  STATE       VARCHAR,
  STREET1     VARCHAR,
  STREET2     VARCHAR,
  ZIPCODE     VARCHAR,
  PRIMARY KEY (ID)
)
